/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-08-05T11:16:32.747Z[GMT]")
@Api(value = "authenticate", description = "the authenticate API")
public interface AuthenticateApi {

    @ApiOperation(value = "Authenticates, via username and password", nickname = "authenticate", notes = "Authenticates, via username and password", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "User name and password accepted"),
        @ApiResponse(code = 401, message = "User not authorised") })
    @RequestMapping(value = "/authenticate",
        method = RequestMethod.POST)
    ResponseEntity<Void> authenticate(@NotNull @ApiParam(value = "user name", required = true) @Valid @RequestParam(value = "username", required = true) String username,@NotNull @ApiParam(value = "passwrod", required = true) @Valid @RequestParam(value = "password", required = true) String password);

}
